// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ADVTalkSystem","status":true,"description":"恋愛ADVのような会話システム","parameters":{"Talk Mode Switch ID":"101","Name Window Switch ID":"102","Center Mode Switch ID":"103","Face Image Switch ID":"104","Fixed Window Switch ID":"105","Fixed Picture Switch ID":"106","Style ID Variable ID":"81","Left Picture ID":"91","Right Picture ID":"92","Message Skip Keys":"shift, control","Hide Window Keys":"pagedown"}}
];
